
version: "3"
services:
  emily-chessbolt-api-0agsq4:
    image: emily-chessbolt-api-0agsq4
    container_name: emily-chessbolt-api-0agsq4
    networks:
      - emily-chessbolt-api-0agsq4-network
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      
    runtime: ${RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: ${IPC}
networks:
  emily-chessbolt-api-0agsq4-network:
    name: emily-chessbolt-api-0agsq4-network
    driver: bridge
  
